### ISSUE TITLE
Please document the MSRV for async-h1

### ISSUE THREAD

**Issue by rbtcollins** [http-rs/async-h1#113]
I used async-std and surf in unleash-client-rust recently, and trying to document the minimum supported rust version for it is turning out harder than expected ;(. async-h1 seems to be using latest-everything features - and thats probably fine, async is new etc, but it would be nice to know what the actual policy is going forward. Just a one liner in README.md. 

Thanks!

(https://github.com/rust-lang/rust/issues/65721 is what caught me trying to make 1.40 the MSRV, which is used by async-h1).

**Comment by yoshuawuyts** [comment]
This is an interesting one -- I have no objections to documenting the MSRV but given the nature of async in Rust right now I would like us to reserve the option to bump the minimum version without publishing a major. In effect the stability guarantee we provide is that we work on stable Rust.
