### ISSUE TITLE
Buffered data while decoding Response

### ISSUE THREAD

**Issue by portgasd666** [http-rs/async-h1#146]
Currently client::decode internally wraps the passed AsyncRead in a BufReader. So if the server sends some data immediately after the HTTP response that is not part of the response body, that data will be lost in the BufReader's inner buffer.

My use case is that I have a server that switches to a custom binary protocol after an initial HTTP request-response exchange where the server sends some data after sending a 200 OK response for example. Is this something the could be supported by this crate ? One solution would be to make the parameter to decode an AsyncBufRead so that the caller has access to the BufReader and can use the unread data in the buffer as needed. This would be similar to the API offered by the GoLang standard HTTP library which is being in used the Go implementation of the same protocol - [ReadResponse](https://golang.org/pkg/net/http/#ReadResponse)

**Comment by jbr** [comment]
Thanks for filing this! Could you explain a bit more about your use case? What does it mean for a server to send additional data that isn't part of the response body? Why isn't it the response body? Is there _also_ a response body? Is there a spec out there that supports this behavior, even if it's not a commonly-used one? I think we're unlikely to expose the buffered data as part of a stable api, so I'm looking for other ways to support the intended functionality

**Comment by jbr** [comment]
It might help to include a sample response to understand what it looks like to the decoder

**Comment by portgasd666** [comment]
Since filing this I've thought about it, this is definitely not behavior conforming to any particular specification so it would be understandable if this was something we wouldn't want to change the API of the decoder for. I'm not sure if I can delve into the details of the protocol itself but basically you think of the flow as being this - 

1. Client creates TLS connection to a Server.
2. Client sends an HTTP Request to the Server. This is mainly meant to authenticate the client before any further data is exchanged
3. Server authenticates the client request and responds with a 200 OK. This response almost always will not have a HTTP response body.
4. At this point the Client and Server switch to some arbitrary binary protocol where further data is exchanged over the same connection.

There is a case where the server may send the HTTP 200OK followed by some data conforming to the arbitrary binary protocol in the same TCP/TLS packet/record. Thats why there is change that when the decoder is decodes the response it reads the full data into the BufReader's buffer and is lost. The way I'm using it in code is something like this -

```
let conn = Arc::new(<tls connect>)
let request = <prepare HTTP request for auth>
let response = async_h1::connect(conn.clone(), request);
// verify 200 OK response
let binary_protocol_message = BinaryProtocol::read(conn); // This never returns since the message has been read in connect
// Do something based on the message
```

Ideally what is needed for this use case is some "low level" API to be able to Encode and Decode an HTTP Request or Response from/to an AsyncRead + AsyncWrite without making any further assumptions about how the connection is used. The current API gives me this except for this small corner case where the buffered data is lost to the caller.

**Comment by jbr** [comment]
I can't make any guarantees about this, but it's possible that the upgrade mechanism we build for websockets may also support this use case. Would you be able to use a http/1.1 Upgrade mechanism and then receive an AsyncRead+AsyncWrite to do whatever with? Do you control the client and server?

How would you expect this to interact with keepalive? Even if you're not using keepalive, we'd need to consider interactions with it for any api we support. async-h1 doesn't yet have functioning keepalive, but 🤞 will soon

**Comment by jbr** [comment]
As async-h1 now supports http/1.1 upgrades, that is our recommended solution to this problem. Closing this issue
