### ISSUE TITLE
Support multiple headers with the same name when decoding into `http_types::Request`

### ISSUE THREAD

**Issue by Enrico2** [http-rs/async-h1#148]
Hi,

We're working on some server code on our end and use Wiremock to test our code. 
Our server supports receiving multiple headers with the same name, as does this crate.

However, we've observed our tests failing when trying to verify all headers with the same name are received.
I've narrowed this down to these lines:
https://github.com/http-rs/async-h1/blob/62735560f7de09e51b314ae06a7f761236dbed41/src/server/decode.rs#L79-L81

I believe the line in the for loop should be
```rust
req.append_header(header.name, std::str::from_utf8(header.value)?);
```

Wiremock uses async-h1 as its lightweight server, and as a result we can't validate our expectation.

Changing this locally compiles and passes all of your tests, but I believe `decode` is not tested.
I'm working on a PR once I write a test case that covers my change.

**Comment by jbr** [comment]
Append looks correct to me (representing a bug), and additional tests would be very welcome but not essential — I'm working on a testing harness for async-h1 that should make it easier to write test cases with less ceremony than our current file fixture approach

**Comment by Enrico2** [comment]
> additional tests would be very welcome but not essential
Great because I'm having a hard time finding a type that satisfies 
`IO: Read + Write + Clone + Send + Sync + Unpin + 'static`

**Comment by Enrico2** [comment]
@jbr PR is up, please lmk when this is released, and hopefully I could also get https://github.com/LukeMathWalker/wiremock-rs to update so it'll unblock our testing. Thanks!

**Comment by jbr** [comment]
@Enrico2 Check out the approach in [tests/continue.rs](https://github.com/http-rs/async-h1/blob/main/tests/continue.rs#L16-L22) for something like the basis of future testing approaches. Coming up with a type that matches those bounds is unfortunately difficult

**Comment by jbr** [comment]
http-types 2.1.4 hot off the presses with this change

**Comment by Enrico2** [comment]
Great, thank you!
