### ISSUE TITLE
Fix Wasm build

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [http-rs/async-h1#154]
Due to that line: https://github.com/http-rs/async-h1/blob/main/src/server/decode.rs#L98
It's impossible to build the library for wasm target.

I see 2 options:
- create a feature to enable client/server. Like that on web only client can be enabled.
- use `spawn_local` as an alias to fix build for wasm target.

It can requires to add build for wasm target on the CI to not reproduce that.

**Comment by jbr** [comment]
I agree that this is worth looking at. When I added that line, I didn't believe that we supported async-h1 on wasm at all.  Can you describe your use case?

**Comment by MarcAntoine-Arnaud** [comment]
I just researching a library to make some http call using async-std library.
I found async-h1 that works perfectly on native.

That's why it don't make 100% sense to keep server compatibility with wasm target.
It's the reason for the option of creating feature for server/client.

But as it don't look very complex, I think it can be awesome to support HTTP Client for Wasm.

**Comment by jbr** [comment]
Thanks! Yes, I agree it would be interesting, but we don't currently support wasm. What transport would you be using? Why would you prefer to use async-h1 to the built-in fetch? Is this for browser or wasi?

If you're interested in making http requests with async-std in wasm, would [surf](https://github.com/http-rs/surf) be an option for you?

**Comment by MarcAntoine-Arnaud** [comment]
I don't wanna to use Fetch as because it's web only.
We are building a cross platform player, for native and web.

I don't expect to have switches in my code.
`surf` is maybe a good alternative to `async-h1`.

**Comment by MarcAntoine-Arnaud** [comment]
I have switch to `surf` and it works perfectly.
I close the issue. Re-open if needed.
