### ISSUE TITLE
CloseableCursor implementation is racey

### ISSUE THREAD

**Issue by Diggsey** [http-rs/async-h1#181]
This is only used by the test suite, but it can cause tests to randomly fail, which is a problem.

The issue is the lack of synchronization between the stored `waker` and the state of the cursor.

There are a few possible fixes:
1) Use a single lock around the entire cursor state, instead of per-field locks.
2) Store the waker *before* performing any operation which might block, or at least re-check if the operation can succeed after storing the waker.
3) Look for a prebuilt solution, it seems like something like this should exist in `futures` or elsewhere.

**Comment by jbr** [comment]
A focused pr with any of these fixes would be welcome 👍. I didn't find anything preexisting, but it fairly general purpose and ideally would not be defined or maintained in async-h1. Preference should be for 3, but since our usage is just for tests, either of the other two that works would be fine
