### ISSUE TITLE
Panic in both client and server: "Empty response"

### ISSUE THREAD

**Issue by Shnatsel** [http-rs/async-h1#184]
This assertion doesn't hold in practice:

https://github.com/http-rs/async-h1/blob/9993b0475ff8909f15907909aefa7e6f8d631732/src/client/decode.rs#L32

This causes panics when using `surf` with `async-h1` backend. 

1525 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/f206362f2e81521bbefb84007cdd25242f6db590/surf-smoke-test/src/main.rs). Test tool output from all affected websites: [surf-panic-empty-response.tar.gz](https://github.com/http-rs/async-h1/files/6054704/surf-panic-empty-response.tar.gz)

**Comment by nullchinchilla** [comment]
I'm seeing this issue too, in production software using `async-h1` (https://github.com/geph-official/geph4). This is letting people trigger crashes on my servers, which is **extremely serious**.

Can a fix be implemented ASAP?

**Comment by jbr** [comment]
Fixed in v2.3.2, thanks for reporting!
