### ISSUE TITLE
Chunked decoding fails on a chunk of length 0xFF7 (4087), 9 bytes less than the buffer size

### ISSUE THREAD

**Issue by joshtriplett** [http-rs/async-h1#195]
Attempting to decode a chunk with length 0xFF7 (4087), exactly 9 bytes less than the buffer size, causes the decoder to stop after that chunk.

I hit this in production, and it was incredibly hard to track down, reproduce, and minimize.

I've written a PR adding a test for this: https://github.com/http-rs/async-h1/pull/194

That test currently fails.

**Comment by jbr** [comment]
Unless @yoshuawuyts has time for this, my proposal would be replacing the chunked decoder with a new one derived from trillium's, since I wrote that and plan to maintain it. As you note

**Comment by jbr** [comment]
We may want to rework https://github.com/trillium-rs/trillium/blob/main/http/src/received_body.rs#L208-284 for use in async-h1 unless @yoshuawuyts has time to look into this

**Comment by yoshuawuyts** [comment]
I'm currently short on time. From the looks of it we should be able to merge trillium's approach without changing the public API in any meaningful way. @jbr I'm on board if you want to do that.
