### ISSUE TITLE
How to send head and body on single tcp packet?

### ISSUE THREAD

**Issue by zousandian** [http-rs/async-h1#198]
When I test the server example, I found the http head and body were sent separately on tcp.
How to send them on single tcp packet? When the body is so small, it's no need to send them separately.

```
cargo run --example server
curl localhost:8080
```

![Screen Shot 2021-12-03 at 15 37 47](https://user-images.githubusercontent.com/6047274/144565131-4c3013ff-5596-4c32-8216-32860c3f5d48.png)

**Comment by yoshuawuyts** [comment]
Consider using a [BufWriter](https://doc.rust-lang.org/std/io/struct.BufWriter.html) around the TcpStream instance you pass so that individual calls to `AsyncWrite::write` with `async-h1` don't directly result in syscalls. This should pack the head and body into a single packet.
