### ISSUE TITLE
Using the underlying connection after sending/receiving HTTP request/response

### ISSUE THREAD

**Issue by portgasd666** [http-rs/async-h1#74]
I have a use case where I need to keep the connection (the RW type in `connect`) open to send more data on it after an initial HTTP request/response exchange. This currently doesn't seem to be possible since the connect function takes ownership of the connection. I know that async-std's TcpStream implements Clone but the same is not the case for async-tls's TlsStream. 

Is this use case supported by this crate ? How would I get around this ?

**Comment by yoshuawuyts** [comment]
@portgasd666 The underlying stream should implement `Clone` which allows you to keep an owned reference for later use. See https://blog.yoshuawuyts.com/io-trait-delegation-for-arc/ for more on this.
