### ISSUE TITLE
Any specific reason why server::decode::decode is not public?

### ISSUE THREAD

**Issue by gdamjan** [http-rs/async-h1#88]
It seems like an useful function to have when one can't use `async_h1::accept`.

**Comment by yoshuawuyts** [comment]
We wanted to keep the API minimal -- encoding and decoding is intended to be done through a stream only. But perhaps there's a way we could fit it in if we move to a struct-based API.

**Comment by gdamjan** [comment]
ok, cool. 

just for context, I'm building a (kind of) proxy with `async_h1`, and while I need the request parsed to act/route on it, I don't need the response parsed, since I can just pass the stream as-is from the back-end to the client. I can't do that with async_h1::accept currently, so I thought to build my own.

looking around, I can't find much standalone http request decoders (parsers).

**Comment by yoshuawuyts** [comment]
@gdamjan It sounds like you're building a TCP and HTTP proxy. Generally parsing the headers on the response is common too for the sake of logging and instrumentation.

If you're looking for a standalone *parser* the [httparse](https://docs.rs/httparse/1.3.4/httparse/) crate handles this for you; but it *only* provides parsing, and correctly handling HTTP requests requires quite a bit more logic than that.

**Comment by gdamjan** [comment]
yes, thank you, I think I'll try that library
