### ISSUE TITLE
Handle Expect header correctly to avoid deadlocks

### ISSUE THREAD

**Issue by Koxiaet** [http-rs/async-h1#93]
[Relevant part of the RFC](https://www.rfc-editor.org/rfc/rfc7231.html#section-5.1.1) - in short, if the server receives an `Expect` header set to `100-continue` (case insensitive), the client won't sent the body of the request until the server responds with an intermediate response (that can't have a body) of `100 Continue`; if a full response is sent then the client won't send the body.

Most clients will have a timeout if the server doesn't respond with 100 Continue and will send the body anyway, but that's not required (it is, but it could be very very long) and so a deadlock could theoretically happen.

**Comment by yoshuawuyts** [comment]
Hey @Koxiaet, thanks for raising this! Ooph; yeah I don't think we were aware of this. Adding this behavior so we match the spec would be great.
