### ISSUE TITLE
Shift deps to `futures`

### ISSUE THREAD

**Issue by hwchen** [http-rs/async-h1#95]
I'm not sure if you're interested in this approach, but I swapped out usage of `async-std` for `futures` (and `futures-timer`). https://github.com/hwchen/async-h1/commit/41f57c6a7878e1cb1b62c5eba74717cd80027814

I saw that there was [mention](https://old.reddit.com/r/rust/comments/f9dg6j/new_post_async_http/firp9ac/) of using a `core` feature in `async-std`. Just using `futures` might simplify even further?

Anyways, my thought is only to use `futures` as much as possible as a clear indicator of async ecosystem compatibility. I'm sure there's many design decisions and trade-offs I don't know about. If you don't feel like discussing, feel free to close, I won't take it personally :) .

**Comment by yoshuawuyts** [comment]
Hey @hwchen, thanks for opening! Yeah, it seems unlikely we'll switch to `futures`. Ecosystem compat stems from `futures-core`, and `futures-io`, which we use as our building blocks. These are the parts that are set for inclusion in the stdlib as well. Using `async-std` provides us access to fast channels and doesn't lock us into using traits such as `Sink` which seem likely to change. We probably won't be changing anytime soon. Hope that makes sense. Thanks!
